stages:
  - build

.build:
  stage: build
  image: coqorg/${CI_JOB_NAME}
  before_script:
    - opam update -y
    - sudo apt-get update -y -q
  script:
    - sudo chown -R coq:coq "$CI_PROJECT_DIR"
    - DEBIAN_FRONTEND=noninteractive sudo apt-get install -y -q shellcheck emacs
    - shellcheck `find -name 'configure'`
    - emacs --batch -l scripts/org-lint-README.el --kill
    - opam pin add -k git -y -j ${NJOBS} coq-ott https://github.com/ott-lang/ott.git
    - opam pin add -k git -y -j ${NJOBS} mi-cho-coq .

coq:8.8:
  extends: .build

coq:8.9:
  extends: .build
